fix: parse json5 codes always thorw JsonException
colinodell/json5 pull request #16
Opened 2021-11-05 17:30 UTC by inhere

## Description

fix: parse json5 codes always thorw JsonException on set JSON_THROW_ON_ERROR

## Motivation and context

Why is this change required? What problem does it solve?

If it fixes an open issue, please link to the issue here (if you write `fixes #num`
or `closes #num`, the issue will be automatically closed when the pull is accepted.)

- close #15 

## How has this been tested?

Please describe in detail how you tested your changes.

Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.

## Sample JSON (if appropriate)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change adds a new code file, I have added the copyright header to it.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

2021-11-05 17:54 UTC, andrew-demb requested changes

2021-11-05 17:54 UTC, andrew-demb commented on src/Json5Decoder.php
> +                $result = \json_decode($source, $associative, $depth, $options | \JSON_THROW_ON_ERROR);
```suggestion
                return \json_decode($source, $associative, $depth, $options | \JSON_THROW_ON_ERROR);
```

2021-11-06 05:17 UTC, colinodell commented
I had to make a couple of small tweaks, mostly because I realized the approach I originally proposed wouldn't work on PHP 7.1 and 7.2 :facepalm:

Thanks for the contribution!

2021-11-06 05:17 UTC, merged

2021-11-06 10:49 UTC, glensc commented
throw typo in title